development:
  cloud_name: "your_cloudinary_cloud_name"
  api_key: "your_api_key"
  api_secret: "your_api_sercret"

production:
  cloud_name: "your_cloudinary_cloud_name"
  api_key: "your_api_key"
  api_secret: "your_api_sercret"
